# Site settings é…ç½®ç«™ç‚¹
title: 'ğŸŒµ Hazelu'
description: 'ğŸ»é€—é€—é…±çš„å°çª'
keyword: 'é€—é€—é…±'
url: 'https://janessasmith.github.io/' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'zhenglu'
nickname: 'janessasmith'
bio: ''
avatar: '/assets/images/avatar.jpg'

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™
sns:
    twitter:    '//twitter.com/emmzooey'
    instagram:  '//instagram.com/emmzooey'
    github:     '//github.com/janessasmith'
    weibo:      '//weibo.com/janessasmith'

# Search
search: true

# Comments è¯„è®ºåŠŸèƒ½
Valine:
    el: 'comment-valine'
    appid: 'P7kjzNADK7TUXDpYqbXFjCNI-gzGzoHsz' #Leancloudåº”ç”¨çš„appId
    appkey: 'tggnWSOKcCk9sbLNTU6QJGvU' #Leancloudåº”ç”¨çš„appKey
    verify: false #éªŒè¯ç 
    notify: true #è¯„è®ºå›å¤æé†’
    placeholder: 'ãƒ¾ï¾‰â‰§âˆ€â‰¦) Just go go~' #è¯„è®ºæ¡†å ä½ç¬¦

# Baidu analytics ç™¾åº¦ç»Ÿè®¡
baidu-analytics: '2af707459a77542d75fd525575b84824'

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM

# RSS
RSS: false

# Plugins
plugins: [jekyll-paginate]